build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd api && make docker-push

    