apiVersion: apps/v1
kind: Deployment
metadata:
  name: photobox
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app.kubernetes.io/instance: photobox
    app.kubernetes.io/name: photobox
    app.kubernetes.io/version: "1.0"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: photobox
      app.kubernetes.io/name: photobox
  template:
      labels:
        app.kubernetes.io/instance: photobox
        app.kubernetes.io/name: photobox
    spec:
      containers:
      - env:
        - name: API_BASE_PATH
          value: /api
        - name: DB_HOST
          value: photobox-mysql
        - name: DB_NAME
          value: photobox_db
        - name: DB_PASSWORD
          value: password
        - name: DB_USER
          value: photobox_usr
        - name: PHOTO_DIR
          value: /photos
        image: registry.gitlab.com/r1chjames/photobox:latest
        imagePullPolicy: IfNotPresent
        name: photobox
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - mountPath: /photos
          name: photos
      imagePullSecrets:
      - name: gitlab-login
      initContainers:
      - command:
        - sh
        - -c
        - until mysqladmin ping -h"photobox-mysql" --silent; do echo waiting for mysql;
          sleep 2; done
        image: mysql
        imagePullPolicy: Always
        name: check-mysql-ready
      volumes:
      - hostPath:
          path: /home/Rich/Pictures
        name: photos