apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
    component: master
    release: photobox
  name: data-photobox-mysql-master-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard