apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: photobox
    meta.helm.sh/release-namespace: default
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: photobox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: photobox
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: photobox-0.1.0
  name: photobox