// Code generated by MockGen. DO NOT EDIT.
// Source: album.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.com/r1chjames/photobox/api/internal/core/domain"
)

// MockAlbumRepository is a mock of AlbumRepository interface.
type MockAlbumRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumRepositoryMockRecorder
}

// MockAlbumRepositoryMockRecorder is the mock recorder for MockAlbumRepository.
type MockAlbumRepositoryMockRecorder struct {
	mock *MockAlbumRepository
}

// NewMockAlbumRepository creates a new mock instance.
func NewMockAlbumRepository(ctrl *gomock.Controller) *MockAlbumRepository {
	mock := &MockAlbumRepository{ctrl: ctrl}
	mock.recorder = &MockAlbumRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbumRepository) EXPECT() *MockAlbumRepositoryMockRecorder {
	return m.recorder
}

// AlbumCount mocks base method.
func (m *MockAlbumRepository) AlbumCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlbumCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlbumCount indicates an expected call of AlbumCount.
func (mr *MockAlbumRepositoryMockRecorder) AlbumCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlbumCount", reflect.TypeOf((*MockAlbumRepository)(nil).AlbumCount))
}

// CreateAlbum mocks base method.
func (m *MockAlbumRepository) CreateAlbum(name string) (*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlbum", name)
	ret0, _ := ret[0].(*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlbum indicates an expected call of CreateAlbum.
func (mr *MockAlbumRepositoryMockRecorder) CreateAlbum(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).CreateAlbum), name)
}

// CreateAlbumIfNotExists mocks base method.
func (m *MockAlbumRepository) CreateAlbumIfNotExists(name string) (*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlbumIfNotExists", name)
	ret0, _ := ret[0].(*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlbumIfNotExists indicates an expected call of CreateAlbumIfNotExists.
func (mr *MockAlbumRepositoryMockRecorder) CreateAlbumIfNotExists(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlbumIfNotExists", reflect.TypeOf((*MockAlbumRepository)(nil).CreateAlbumIfNotExists), name)
}

// DeleteAlbum mocks base method.
func (m *MockAlbumRepository) DeleteAlbum(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlbum", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlbum indicates an expected call of DeleteAlbum.
func (mr *MockAlbumRepositoryMockRecorder) DeleteAlbum(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).DeleteAlbum), id)
}

// GetAlbumById mocks base method.
func (m *MockAlbumRepository) GetAlbumById(id string) (*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumById", id)
	ret0, _ := ret[0].(*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumById indicates an expected call of GetAlbumById.
func (mr *MockAlbumRepositoryMockRecorder) GetAlbumById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumById", reflect.TypeOf((*MockAlbumRepository)(nil).GetAlbumById), id)
}

// GetAlbumByName mocks base method.
func (m *MockAlbumRepository) GetAlbumByName(name string) (*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumByName", name)
	ret0, _ := ret[0].(*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumByName indicates an expected call of GetAlbumByName.
func (mr *MockAlbumRepositoryMockRecorder) GetAlbumByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumByName", reflect.TypeOf((*MockAlbumRepository)(nil).GetAlbumByName), name)
}

// ListAllAlbums mocks base method.
func (m *MockAlbumRepository) ListAllAlbums(fromId string, pageSize int) ([]*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllAlbums", fromId, pageSize)
	ret0, _ := ret[0].([]*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllAlbums indicates an expected call of ListAllAlbums.
func (mr *MockAlbumRepositoryMockRecorder) ListAllAlbums(fromId, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllAlbums", reflect.TypeOf((*MockAlbumRepository)(nil).ListAllAlbums), fromId, pageSize)
}

// ReassignPhotosToAlbum mocks base method.
func (m *MockAlbumRepository) ReassignPhotosToAlbum(fromAlbumId, toAlbumId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignPhotosToAlbum", fromAlbumId, toAlbumId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignPhotosToAlbum indicates an expected call of ReassignPhotosToAlbum.
func (mr *MockAlbumRepositoryMockRecorder) ReassignPhotosToAlbum(fromAlbumId, toAlbumId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignPhotosToAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).ReassignPhotosToAlbum), fromAlbumId, toAlbumId)
}

// SearchAlbums mocks base method.
func (m *MockAlbumRepository) SearchAlbums(query string, limit int) ([]*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAlbums", query, limit)
	ret0, _ := ret[0].([]*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAlbums indicates an expected call of SearchAlbums.
func (mr *MockAlbumRepositoryMockRecorder) SearchAlbums(query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAlbums", reflect.TypeOf((*MockAlbumRepository)(nil).SearchAlbums), query, limit)
}

// UpdateAlbum mocks base method.
func (m *MockAlbumRepository) UpdateAlbum(album *domain.Album) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlbum", album)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAlbum indicates an expected call of UpdateAlbum.
func (mr *MockAlbumRepositoryMockRecorder) UpdateAlbum(album interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlbum", reflect.TypeOf((*MockAlbumRepository)(nil).UpdateAlbum), album)
}

// MockAlbumService is a mock of AlbumService interface.
type MockAlbumService struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumServiceMockRecorder
}

// MockAlbumServiceMockRecorder is the mock recorder for MockAlbumService.
type MockAlbumServiceMockRecorder struct {
	mock *MockAlbumService
}

// NewMockAlbumService creates a new mock instance.
func NewMockAlbumService(ctrl *gomock.Controller) *MockAlbumService {
	mock := &MockAlbumService{ctrl: ctrl}
	mock.recorder = &MockAlbumServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbumService) EXPECT() *MockAlbumServiceMockRecorder {
	return m.recorder
}

// AlbumCount mocks base method.
func (m *MockAlbumService) AlbumCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlbumCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlbumCount indicates an expected call of AlbumCount.
func (mr *MockAlbumServiceMockRecorder) AlbumCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlbumCount", reflect.TypeOf((*MockAlbumService)(nil).AlbumCount))
}

// CreateAlbum mocks base method.
func (m *MockAlbumService) CreateAlbum(name string) (*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlbum", name)
	ret0, _ := ret[0].(*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlbum indicates an expected call of CreateAlbum.
func (mr *MockAlbumServiceMockRecorder) CreateAlbum(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlbum", reflect.TypeOf((*MockAlbumService)(nil).CreateAlbum), name)
}

// DeleteAlbum mocks base method.
func (m *MockAlbumService) DeleteAlbum(id string, deletePhotos bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlbum", id, deletePhotos)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlbum indicates an expected call of DeleteAlbum.
func (mr *MockAlbumServiceMockRecorder) DeleteAlbum(id, deletePhotos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlbum", reflect.TypeOf((*MockAlbumService)(nil).DeleteAlbum), id, deletePhotos)
}

// GetAlbumById mocks base method.
func (m *MockAlbumService) GetAlbumById(id string) (*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumById", id)
	ret0, _ := ret[0].(*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumById indicates an expected call of GetAlbumById.
func (mr *MockAlbumServiceMockRecorder) GetAlbumById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumById", reflect.TypeOf((*MockAlbumService)(nil).GetAlbumById), id)
}

// GetAlbumByName mocks base method.
func (m *MockAlbumService) GetAlbumByName(name string) (*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumByName", name)
	ret0, _ := ret[0].(*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumByName indicates an expected call of GetAlbumByName.
func (mr *MockAlbumServiceMockRecorder) GetAlbumByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumByName", reflect.TypeOf((*MockAlbumService)(nil).GetAlbumByName), name)
}

// ListAlbums mocks base method.
func (m *MockAlbumService) ListAlbums(fromId string, limit int) ([]*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlbums", fromId, limit)
	ret0, _ := ret[0].([]*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAlbums indicates an expected call of ListAlbums.
func (mr *MockAlbumServiceMockRecorder) ListAlbums(fromId, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlbums", reflect.TypeOf((*MockAlbumService)(nil).ListAlbums), fromId, limit)
}

// SearchAlbums mocks base method.
func (m *MockAlbumService) SearchAlbums(query string, limit int) ([]*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAlbums", query, limit)
	ret0, _ := ret[0].([]*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAlbums indicates an expected call of SearchAlbums.
func (mr *MockAlbumServiceMockRecorder) SearchAlbums(query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAlbums", reflect.TypeOf((*MockAlbumService)(nil).SearchAlbums), query, limit)
}

// UpdateAlbum mocks base method.
func (m *MockAlbumService) UpdateAlbum(id string, updates map[string]any) (*domain.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlbum", id, updates)
	ret0, _ := ret[0].(*domain.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAlbum indicates an expected call of UpdateAlbum.
func (mr *MockAlbumServiceMockRecorder) UpdateAlbum(id, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlbum", reflect.TypeOf((*MockAlbumService)(nil).UpdateAlbum), id, updates)
}
