// Code generated by MockGen. DO NOT EDIT.
// Source: filesystem.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	exif "github.com/rwcarlsen/goexif/exif"
	domain "gitlab.com/r1chjames/photobox/api/internal/core/domain"
)

// MockFilesystemRepository is a mock of FilesystemRepository interface.
type MockFilesystemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFilesystemRepositoryMockRecorder
}

// MockFilesystemRepositoryMockRecorder is the mock recorder for MockFilesystemRepository.
type MockFilesystemRepositoryMockRecorder struct {
	mock *MockFilesystemRepository
}

// NewMockFilesystemRepository creates a new mock instance.
func NewMockFilesystemRepository(ctrl *gomock.Controller) *MockFilesystemRepository {
	mock := &MockFilesystemRepository{ctrl: ctrl}
	mock.recorder = &MockFilesystemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesystemRepository) EXPECT() *MockFilesystemRepositoryMockRecorder {
	return m.recorder
}

// CreateDirectoryIfNotExists mocks base method.
func (m *MockFilesystemRepository) CreateDirectoryIfNotExists(basePhotoPath, directoryName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateDirectoryIfNotExists", basePhotoPath, directoryName)
}

// CreateDirectoryIfNotExists indicates an expected call of CreateDirectoryIfNotExists.
func (mr *MockFilesystemRepositoryMockRecorder) CreateDirectoryIfNotExists(basePhotoPath, directoryName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDirectoryIfNotExists", reflect.TypeOf((*MockFilesystemRepository)(nil).CreateDirectoryIfNotExists), basePhotoPath, directoryName)
}

// GenerateThumbnail mocks base method.
func (m *MockFilesystemRepository) GenerateThumbnail(path string, width, height int) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateThumbnail", path, width, height)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GenerateThumbnail indicates an expected call of GenerateThumbnail.
func (mr *MockFilesystemRepositoryMockRecorder) GenerateThumbnail(path, width, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateThumbnail", reflect.TypeOf((*MockFilesystemRepository)(nil).GenerateThumbnail), path, width, height)
}

// MoveToTrash mocks base method.
func (m *MockFilesystemRepository) MoveToTrash(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToTrash", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveToTrash indicates an expected call of MoveToTrash.
func (mr *MockFilesystemRepositoryMockRecorder) MoveToTrash(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToTrash", reflect.TypeOf((*MockFilesystemRepository)(nil).MoveToTrash), path)
}

// RenameDirectory mocks base method.
func (m *MockFilesystemRepository) RenameDirectory(oldPath, newPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameDirectory", oldPath, newPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameDirectory indicates an expected call of RenameDirectory.
func (mr *MockFilesystemRepositoryMockRecorder) RenameDirectory(oldPath, newPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameDirectory", reflect.TypeOf((*MockFilesystemRepository)(nil).RenameDirectory), oldPath, newPath)
}

// RestoreFromTrash mocks base method.
func (m *MockFilesystemRepository) RestoreFromTrash(trashPath, originalPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreFromTrash", trashPath, originalPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreFromTrash indicates an expected call of RestoreFromTrash.
func (mr *MockFilesystemRepositoryMockRecorder) RestoreFromTrash(trashPath, originalPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreFromTrash", reflect.TypeOf((*MockFilesystemRepository)(nil).RestoreFromTrash), trashPath, originalPath)
}

// ScanFilesystem mocks base method.
func (m *MockFilesystemRepository) ScanFilesystem(photoChan chan string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ScanFilesystem", photoChan)
}

// ScanFilesystem indicates an expected call of ScanFilesystem.
func (mr *MockFilesystemRepositoryMockRecorder) ScanFilesystem(photoChan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanFilesystem", reflect.TypeOf((*MockFilesystemRepository)(nil).ScanFilesystem), photoChan)
}

// MockFilesystemService is a mock of FilesystemService interface.
type MockFilesystemService struct {
	ctrl     *gomock.Controller
	recorder *MockFilesystemServiceMockRecorder
}

// MockFilesystemServiceMockRecorder is the mock recorder for MockFilesystemService.
type MockFilesystemServiceMockRecorder struct {
	mock *MockFilesystemService
}

// NewMockFilesystemService creates a new mock instance.
func NewMockFilesystemService(ctrl *gomock.Controller) *MockFilesystemService {
	mock := &MockFilesystemService{ctrl: ctrl}
	mock.recorder = &MockFilesystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesystemService) EXPECT() *MockFilesystemServiceMockRecorder {
	return m.recorder
}

// GenerateThumbnail mocks base method.
func (m *MockFilesystemService) GenerateThumbnail(path string, exifData exif.Exif, width, height int) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateThumbnail", path, exifData, width, height)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GenerateThumbnail indicates an expected call of GenerateThumbnail.
func (mr *MockFilesystemServiceMockRecorder) GenerateThumbnail(path, exifData, width, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateThumbnail", reflect.TypeOf((*MockFilesystemService)(nil).GenerateThumbnail), path, exifData, width, height)
}

// MoveToTrash mocks base method.
func (m *MockFilesystemService) MoveToTrash(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToTrash", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveToTrash indicates an expected call of MoveToTrash.
func (mr *MockFilesystemServiceMockRecorder) MoveToTrash(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToTrash", reflect.TypeOf((*MockFilesystemService)(nil).MoveToTrash), path)
}

// PerformPhotoIndex mocks base method.
func (m *MockFilesystemService) PerformPhotoIndex(save func([]domain.PhotoFile) error, indexCache map[string]struct{ FileHash string; FileModifiedTime int64 }) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PerformPhotoIndex", save, indexCache)
}

// PerformPhotoIndex indicates an expected call of PerformPhotoIndex.
func (mr *MockFilesystemServiceMockRecorder) PerformPhotoIndex(save, indexCache interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformPhotoIndex", reflect.TypeOf((*MockFilesystemService)(nil).PerformPhotoIndex), save, indexCache)
}

// RenameDirectory mocks base method.
func (m *MockFilesystemService) RenameDirectory(oldPath, newPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameDirectory", oldPath, newPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameDirectory indicates an expected call of RenameDirectory.
func (mr *MockFilesystemServiceMockRecorder) RenameDirectory(oldPath, newPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameDirectory", reflect.TypeOf((*MockFilesystemService)(nil).RenameDirectory), oldPath, newPath)
}

// RestoreFromTrash mocks base method.
func (m *MockFilesystemService) RestoreFromTrash(trashPath, originalPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreFromTrash", trashPath, originalPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreFromTrash indicates an expected call of RestoreFromTrash.
func (mr *MockFilesystemServiceMockRecorder) RestoreFromTrash(trashPath, originalPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreFromTrash", reflect.TypeOf((*MockFilesystemService)(nil).RestoreFromTrash), trashPath, originalPath)
}

// WriteFileToFilesystem mocks base method.
func (m *MockFilesystemService) WriteFileToFilesystem(photo domain.PhotoUpload) domain.PhotoFile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFileToFilesystem", photo)
	ret0, _ := ret[0].(domain.PhotoFile)
	return ret0
}

// WriteFileToFilesystem indicates an expected call of WriteFileToFilesystem.
func (mr *MockFilesystemServiceMockRecorder) WriteFileToFilesystem(photo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFileToFilesystem", reflect.TypeOf((*MockFilesystemService)(nil).WriteFileToFilesystem), photo)
}
