// Code generated by MockGen. DO NOT EDIT.
// Source: job.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.com/r1chjames/photobox/api/internal/core/domain"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// CreateBaseJobs mocks base method.
func (m *MockJobRepository) CreateBaseJobs() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBaseJobs")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBaseJobs indicates an expected call of CreateBaseJobs.
func (mr *MockJobRepositoryMockRecorder) CreateBaseJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBaseJobs", reflect.TypeOf((*MockJobRepository)(nil).CreateBaseJobs))
}

// GetAllJobs mocks base method.
func (m *MockJobRepository) GetAllJobs() ([]domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllJobs")
	ret0, _ := ret[0].([]domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllJobs indicates an expected call of GetAllJobs.
func (mr *MockJobRepositoryMockRecorder) GetAllJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllJobs", reflect.TypeOf((*MockJobRepository)(nil).GetAllJobs))
}

// IsJobRunning mocks base method.
func (m *MockJobRepository) IsJobRunning(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsJobRunning", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsJobRunning indicates an expected call of IsJobRunning.
func (mr *MockJobRepositoryMockRecorder) IsJobRunning(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsJobRunning", reflect.TypeOf((*MockJobRepository)(nil).IsJobRunning), name)
}

// StartJobIfNotRunning mocks base method.
func (m *MockJobRepository) StartJobIfNotRunning(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartJobIfNotRunning", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartJobIfNotRunning indicates an expected call of StartJobIfNotRunning.
func (mr *MockJobRepositoryMockRecorder) StartJobIfNotRunning(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartJobIfNotRunning", reflect.TypeOf((*MockJobRepository)(nil).StartJobIfNotRunning), name)
}

// UpdateAllJobsStatus mocks base method.
func (m *MockJobRepository) UpdateAllJobsStatus(status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllJobsStatus", status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAllJobsStatus indicates an expected call of UpdateAllJobsStatus.
func (mr *MockJobRepositoryMockRecorder) UpdateAllJobsStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllJobsStatus", reflect.TypeOf((*MockJobRepository)(nil).UpdateAllJobsStatus), status)
}

// UpdateJobStatus mocks base method.
func (m *MockJobRepository) UpdateJobStatus(name, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobStatus", name, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobStatus indicates an expected call of UpdateJobStatus.
func (mr *MockJobRepositoryMockRecorder) UpdateJobStatus(name, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobStatus", reflect.TypeOf((*MockJobRepository)(nil).UpdateJobStatus), name, status)
}

// MockJobService is a mock of JobService interface.
type MockJobService struct {
	ctrl     *gomock.Controller
	recorder *MockJobServiceMockRecorder
}

// MockJobServiceMockRecorder is the mock recorder for MockJobService.
type MockJobServiceMockRecorder struct {
	mock *MockJobService
}

// NewMockJobService creates a new mock instance.
func NewMockJobService(ctrl *gomock.Controller) *MockJobService {
	mock := &MockJobService{ctrl: ctrl}
	mock.recorder = &MockJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobService) EXPECT() *MockJobServiceMockRecorder {
	return m.recorder
}

// CreateBaseJobs mocks base method.
func (m *MockJobService) CreateBaseJobs() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBaseJobs")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBaseJobs indicates an expected call of CreateBaseJobs.
func (mr *MockJobServiceMockRecorder) CreateBaseJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBaseJobs", reflect.TypeOf((*MockJobService)(nil).CreateBaseJobs))
}

// GetAllJobs mocks base method.
func (m *MockJobService) GetAllJobs() ([]domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllJobs")
	ret0, _ := ret[0].([]domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllJobs indicates an expected call of GetAllJobs.
func (mr *MockJobServiceMockRecorder) GetAllJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllJobs", reflect.TypeOf((*MockJobService)(nil).GetAllJobs))
}

// IsJobRunning mocks base method.
func (m *MockJobService) IsJobRunning(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsJobRunning", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsJobRunning indicates an expected call of IsJobRunning.
func (mr *MockJobServiceMockRecorder) IsJobRunning(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsJobRunning", reflect.TypeOf((*MockJobService)(nil).IsJobRunning), name)
}

// JobComplete mocks base method.
func (m *MockJobService) JobComplete(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobComplete", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// JobComplete indicates an expected call of JobComplete.
func (mr *MockJobServiceMockRecorder) JobComplete(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobComplete", reflect.TypeOf((*MockJobService)(nil).JobComplete), name)
}

// JobStart mocks base method.
func (m *MockJobService) JobStart(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobStart", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// JobStart indicates an expected call of JobStart.
func (mr *MockJobServiceMockRecorder) JobStart(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobStart", reflect.TypeOf((*MockJobService)(nil).JobStart), name)
}

// StartJobIfNotRunning mocks base method.
func (m *MockJobService) StartJobIfNotRunning(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartJobIfNotRunning", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartJobIfNotRunning indicates an expected call of StartJobIfNotRunning.
func (mr *MockJobServiceMockRecorder) StartJobIfNotRunning(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartJobIfNotRunning", reflect.TypeOf((*MockJobService)(nil).StartJobIfNotRunning), name)
}

// UpdateAllJobsStatus mocks base method.
func (m *MockJobService) UpdateAllJobsStatus(status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllJobsStatus", status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAllJobsStatus indicates an expected call of UpdateAllJobsStatus.
func (mr *MockJobServiceMockRecorder) UpdateAllJobsStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllJobsStatus", reflect.TypeOf((*MockJobService)(nil).UpdateAllJobsStatus), status)
}
