// Code generated by MockGen. DO NOT EDIT.
// Source: photo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.com/r1chjames/photobox/api/internal/core/domain"
)

// MockPhotoRepository is a mock of PhotoRepository interface.
type MockPhotoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoRepositoryMockRecorder
}

// MockPhotoRepositoryMockRecorder is the mock recorder for MockPhotoRepository.
type MockPhotoRepositoryMockRecorder struct {
	mock *MockPhotoRepository
}

// NewMockPhotoRepository creates a new mock instance.
func NewMockPhotoRepository(ctrl *gomock.Controller) *MockPhotoRepository {
	mock := &MockPhotoRepository{ctrl: ctrl}
	mock.recorder = &MockPhotoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoRepository) EXPECT() *MockPhotoRepositoryMockRecorder {
	return m.recorder
}

// CreatePhotoInfo mocks base method.
func (m *MockPhotoRepository) CreatePhotoInfo(photo domain.Photo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePhotoInfo", photo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePhotoInfo indicates an expected call of CreatePhotoInfo.
func (mr *MockPhotoRepositoryMockRecorder) CreatePhotoInfo(photo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePhotoInfo", reflect.TypeOf((*MockPhotoRepository)(nil).CreatePhotoInfo), photo)
}

// CreatePhotosInfo mocks base method.
func (m *MockPhotoRepository) CreatePhotosInfo(photos []domain.Photo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePhotosInfo", photos)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePhotosInfo indicates an expected call of CreatePhotosInfo.
func (mr *MockPhotoRepositoryMockRecorder) CreatePhotosInfo(photos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePhotosInfo", reflect.TypeOf((*MockPhotoRepository)(nil).CreatePhotosInfo), photos)
}

// EmptyTrash mocks base method.
func (m *MockPhotoRepository) EmptyTrash() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmptyTrash")
	ret0, _ := ret[0].(error)
	return ret0
}

// EmptyTrash indicates an expected call of EmptyTrash.
func (mr *MockPhotoRepositoryMockRecorder) EmptyTrash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmptyTrash", reflect.TypeOf((*MockPhotoRepository)(nil).EmptyTrash))
}

// ListExpiredTrashPhotos mocks base method.
func (m *MockPhotoRepository) ListExpiredTrashPhotos(cutoff time.Time) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredTrashPhotos", cutoff)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredTrashPhotos indicates an expected call of ListExpiredTrashPhotos.
func (mr *MockPhotoRepositoryMockRecorder) ListExpiredTrashPhotos(cutoff interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredTrashPhotos", reflect.TypeOf((*MockPhotoRepository)(nil).ListExpiredTrashPhotos), cutoff)
}

// PermanentlyDeletePhotos mocks base method.
func (m *MockPhotoRepository) PermanentlyDeletePhotos(photoIds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermanentlyDeletePhotos", photoIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// PermanentlyDeletePhotos indicates an expected call of PermanentlyDeletePhotos.
func (mr *MockPhotoRepositoryMockRecorder) PermanentlyDeletePhotos(photoIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermanentlyDeletePhotos", reflect.TypeOf((*MockPhotoRepository)(nil).PermanentlyDeletePhotos), photoIds)
}

// GetAllTags mocks base method.
func (m *MockPhotoRepository) GetAllTags() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTags")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTags indicates an expected call of GetAllTags.
func (mr *MockPhotoRepositoryMockRecorder) GetAllTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTags", reflect.TypeOf((*MockPhotoRepository)(nil).GetAllTags))
}

// GetPhotoTags mocks base method.
func (m *MockPhotoRepository) GetPhotoTags(photoId string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoTags", photoId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotoTags indicates an expected call of GetPhotoTags.
func (mr *MockPhotoRepositoryMockRecorder) GetPhotoTags(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoTags", reflect.TypeOf((*MockPhotoRepository)(nil).GetPhotoTags), photoId)
}

// GetDuplicatePhotos mocks base method.
func (m *MockPhotoRepository) GetDuplicatePhotos() ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDuplicatePhotos")
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDuplicatePhotos indicates an expected call of GetDuplicatePhotos.
func (mr *MockPhotoRepositoryMockRecorder) GetDuplicatePhotos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDuplicatePhotos", reflect.TypeOf((*MockPhotoRepository)(nil).GetDuplicatePhotos))
}

// GetPhotoById mocks base method.
func (m *MockPhotoRepository) GetPhotoById(photoId string, includeThumbnail bool) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoById", photoId, includeThumbnail)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotoById indicates an expected call of GetPhotoById.
func (mr *MockPhotoRepositoryMockRecorder) GetPhotoById(photoId, includeThumbnail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoById", reflect.TypeOf((*MockPhotoRepository)(nil).GetPhotoById), photoId, includeThumbnail)
}

// GetPhotoThumbnails mocks base method.
func (m *MockPhotoRepository) GetPhotoThumbnails(photoIds []string) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoThumbnails", photoIds)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotoThumbnails indicates an expected call of GetPhotoThumbnails.
func (mr *MockPhotoRepositoryMockRecorder) GetPhotoThumbnails(photoIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoThumbnails", reflect.TypeOf((*MockPhotoRepository)(nil).GetPhotoThumbnails), photoIds)
}

// GetPhotosInAlbumCount mocks base method.
func (m *MockPhotoRepository) GetPhotosInAlbumCount(albumId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotosInAlbumCount", albumId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotosInAlbumCount indicates an expected call of GetPhotosInAlbumCount.
func (mr *MockPhotoRepositoryMockRecorder) GetPhotosInAlbumCount(albumId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotosInAlbumCount", reflect.TypeOf((*MockPhotoRepository)(nil).GetPhotosInAlbumCount), albumId)
}

// GetPhotosWithGeodata mocks base method.
func (m *MockPhotoRepository) GetPhotosWithGeodata(north, south, east, west float64) ([]domain.PhotoGeoData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotosWithGeodata", north, south, east, west)
	ret0, _ := ret[0].([]domain.PhotoGeoData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotosWithGeodata indicates an expected call of GetPhotosWithGeodata.
func (mr *MockPhotoRepositoryMockRecorder) GetPhotosWithGeodata(north, south, east, west interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotosWithGeodata", reflect.TypeOf((*MockPhotoRepository)(nil).GetPhotosWithGeodata), north, south, east, west)
}

// GetThumbnailBytes mocks base method.
func (m *MockPhotoRepository) GetThumbnailBytes(photoId string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThumbnailBytes", photoId)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThumbnailBytes indicates an expected call of GetThumbnailBytes.
func (mr *MockPhotoRepositoryMockRecorder) GetThumbnailBytes(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThumbnailBytes", reflect.TypeOf((*MockPhotoRepository)(nil).GetThumbnailBytes), photoId)
}

// GetThumbnailPath mocks base method.
func (m *MockPhotoRepository) GetThumbnailPath(photoId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThumbnailPath", photoId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThumbnailPath indicates an expected call of GetThumbnailPath.
func (mr *MockPhotoRepositoryMockRecorder) GetThumbnailPath(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThumbnailPath", reflect.TypeOf((*MockPhotoRepository)(nil).GetThumbnailPath), photoId)
}

// GetTimeline mocks base method.
func (m *MockPhotoRepository) GetTimeline() ([]domain.TimelineEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeline")
	ret0, _ := ret[0].([]domain.TimelineEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeline indicates an expected call of GetTimeline.
func (mr *MockPhotoRepositoryMockRecorder) GetTimeline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeline", reflect.TypeOf((*MockPhotoRepository)(nil).GetTimeline))
}

// ListAllPhotos mocks base method.
func (m *MockPhotoRepository) ListAllPhotos(fromId string, limit int, includeThumbnail bool, startDate, endDate, mediaType string) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPhotos", fromId, limit, includeThumbnail, startDate, endDate, mediaType)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPhotos indicates an expected call of ListAllPhotos.
func (mr *MockPhotoRepositoryMockRecorder) ListAllPhotos(fromId, limit, includeThumbnail, startDate, endDate, mediaType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPhotos", reflect.TypeOf((*MockPhotoRepository)(nil).ListAllPhotos), fromId, limit, includeThumbnail, startDate, endDate, mediaType)
}

// ListAllPhotosInAlbum mocks base method.
func (m *MockPhotoRepository) ListAllPhotosInAlbum(albumId, fromId string, limit int, includeThumbnail bool, startDate, endDate, mediaType string) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPhotosInAlbum", albumId, fromId, limit, includeThumbnail, startDate, endDate, mediaType)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPhotosInAlbum indicates an expected call of ListAllPhotosInAlbum.
func (mr *MockPhotoRepositoryMockRecorder) ListAllPhotosInAlbum(albumId, fromId, limit, includeThumbnail, startDate, endDate, mediaType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPhotosInAlbum", reflect.TypeOf((*MockPhotoRepository)(nil).ListAllPhotosInAlbum), albumId, fromId, limit, includeThumbnail, startDate, endDate, mediaType)
}

// ListFavoritePhotos mocks base method.
func (m *MockPhotoRepository) ListFavoritePhotos(fromId string, limit int, includeThumbnail bool, startDate, endDate string) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavoritePhotos", fromId, limit, includeThumbnail, startDate, endDate)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLowQualityPhotos mocks base method.
func (m *MockPhotoRepository) ListLowQualityPhotos(fromId string, limit int, includeThumbnail bool) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLowQualityPhotos", fromId, limit, includeThumbnail)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnscoredPhotos mocks base method.
func (m *MockPhotoRepository) ListUnscoredPhotos(limit int) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnscoredPhotos", limit)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnscoredPhotos indicates an expected call of ListUnscoredPhotos.
func (mr *MockPhotoRepositoryMockRecorder) ListUnscoredPhotos(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnscoredPhotos", reflect.TypeOf((*MockPhotoRepository)(nil).ListUnscoredPhotos), limit)
}

// UpdatePhotoQuality mocks base method.
func (m *MockPhotoRepository) UpdatePhotoQuality(photoId string, qualityScore int, blurScore float64, isLowQuality bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhotoQuality", photoId, qualityScore, blurScore, isLowQuality)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePhotoQuality indicates an expected call of UpdatePhotoQuality.
func (mr *MockPhotoRepositoryMockRecorder) UpdatePhotoQuality(photoId, qualityScore, blurScore, isLowQuality interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhotoQuality", reflect.TypeOf((*MockPhotoRepository)(nil).UpdatePhotoQuality), photoId, qualityScore, blurScore, isLowQuality)
}

// ListLowQualityPhotos indicates an expected call of ListLowQualityPhotos.
func (mr *MockPhotoRepositoryMockRecorder) ListLowQualityPhotos(fromId, limit, includeThumbnail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLowQualityPhotos", reflect.TypeOf((*MockPhotoRepository)(nil).ListLowQualityPhotos), fromId, limit, includeThumbnail)
}

// ListFavoritePhotos indicates an expected call of ListFavoritePhotos.
func (mr *MockPhotoRepositoryMockRecorder) ListFavoritePhotos(fromId, limit, includeThumbnail, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavoritePhotos", reflect.TypeOf((*MockPhotoRepository)(nil).ListFavoritePhotos), fromId, limit, includeThumbnail, startDate, endDate)
}

// ListPhotosByTags mocks base method.
func (m *MockPhotoRepository) ListPhotosByTags(tags []string, fromId string, limit int, includeThumbnail bool) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPhotosByTags", tags, fromId, limit, includeThumbnail)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPhotosByTags indicates an expected call of ListPhotosByTags.
func (mr *MockPhotoRepositoryMockRecorder) ListPhotosByTags(tags, fromId, limit, includeThumbnail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPhotosByTags", reflect.TypeOf((*MockPhotoRepository)(nil).ListPhotosByTags), tags, fromId, limit, includeThumbnail)
}

// ListTrashPhotos mocks base method.
func (m *MockPhotoRepository) ListTrashPhotos(fromId string, limit int, includeThumbnail bool) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrashPhotos", fromId, limit, includeThumbnail)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrashPhotos indicates an expected call of ListTrashPhotos.
func (mr *MockPhotoRepositoryMockRecorder) ListTrashPhotos(fromId, limit, includeThumbnail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrashPhotos", reflect.TypeOf((*MockPhotoRepository)(nil).ListTrashPhotos), fromId, limit, includeThumbnail)
}

// RestorePhoto mocks base method.
func (m *MockPhotoRepository) RestorePhoto(photoId string) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestorePhoto", photoId)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestorePhoto indicates an expected call of RestorePhoto.
func (mr *MockPhotoRepositoryMockRecorder) RestorePhoto(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestorePhoto", reflect.TypeOf((*MockPhotoRepository)(nil).RestorePhoto), photoId)
}

// SearchPhotos mocks base method.
func (m *MockPhotoRepository) SearchPhotos(query string, limit int) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPhotos", query, limit)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPhotos indicates an expected call of SearchPhotos.
func (mr *MockPhotoRepositoryMockRecorder) SearchPhotos(query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPhotos", reflect.TypeOf((*MockPhotoRepository)(nil).SearchPhotos), query, limit)
}

// SetFavorite mocks base method.
func (m *MockPhotoRepository) SetFavorite(photoId string, favorite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFavorite", photoId, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFavorite indicates an expected call of SetFavorite.
func (mr *MockPhotoRepositoryMockRecorder) SetFavorite(photoId, favorite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFavorite", reflect.TypeOf((*MockPhotoRepository)(nil).SetFavorite), photoId, favorite)
}

// SetFavoriteForPhotos mocks base method.
func (m *MockPhotoRepository) SetFavoriteForPhotos(photoIds []string, favorite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFavoriteForPhotos", photoIds, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFavoriteForPhotos indicates an expected call of SetFavoriteForPhotos.
func (mr *MockPhotoRepositoryMockRecorder) SetFavoriteForPhotos(photoIds, favorite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFavoriteForPhotos", reflect.TypeOf((*MockPhotoRepository)(nil).SetFavoriteForPhotos), photoIds, favorite)
}

// AssignPhotosToAlbum mocks base method.
func (m *MockPhotoRepository) AssignPhotosToAlbum(photoIds []string, albumId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPhotosToAlbum", photoIds, albumId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignPhotosToAlbum indicates an expected call of AssignPhotosToAlbum.
func (mr *MockPhotoRepositoryMockRecorder) AssignPhotosToAlbum(photoIds, albumId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPhotosToAlbum", reflect.TypeOf((*MockPhotoRepository)(nil).AssignPhotosToAlbum), photoIds, albumId)
}

// SoftDeletePhoto mocks base method.
func (m *MockPhotoRepository) SoftDeletePhoto(photoId string) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeletePhoto", photoId)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeletePhoto indicates an expected call of SoftDeletePhoto.
func (mr *MockPhotoRepositoryMockRecorder) SoftDeletePhoto(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeletePhoto", reflect.TypeOf((*MockPhotoRepository)(nil).SoftDeletePhoto), photoId)
}

// UpdatePhoto mocks base method.
func (m *MockPhotoRepository) UpdatePhoto(photo domain.Photo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhoto", photo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePhotoMetadata mocks base method.
func (m *MockPhotoRepository) UpdatePhotoMetadata(photoId string, updates domain.Photo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhotoMetadata", photoId, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePhotoMetadata indicates an expected call of UpdatePhotoMetadata.
func (mr *MockPhotoRepositoryMockRecorder) UpdatePhotoMetadata(photoId, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhotoMetadata", reflect.TypeOf((*MockPhotoRepository)(nil).UpdatePhotoMetadata), photoId, updates)
}

// UpdatePhoto indicates an expected call of UpdatePhoto.
func (mr *MockPhotoRepositoryMockRecorder) UpdatePhoto(photo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhoto", reflect.TypeOf((*MockPhotoRepository)(nil).UpdatePhoto), photo)
}

// UpdatePhotoTags mocks base method.
func (m *MockPhotoRepository) UpdatePhotoTags(photoId, tags string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhotoTags", photoId, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePhotoTags indicates an expected call of UpdatePhotoTags.
func (mr *MockPhotoRepositoryMockRecorder) UpdatePhotoTags(photoId, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhotoTags", reflect.TypeOf((*MockPhotoRepository)(nil).UpdatePhotoTags), photoId, tags)
}

// AddAITags mocks base method.
func (m *MockPhotoRepository) AddAITags(photoId string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAITags", photoId, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAITags indicates an expected call of AddAITags.
func (mr *MockPhotoRepositoryMockRecorder) AddAITags(photoId, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAITags", reflect.TypeOf((*MockPhotoRepository)(nil).AddAITags), photoId, tags)
}

// ListPhotosWithoutAITags mocks base method.
func (m *MockPhotoRepository) ListPhotosWithoutAITags(limit int) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPhotosWithoutAITags", limit)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPhotosWithoutAITags indicates an expected call of ListPhotosWithoutAITags.
func (mr *MockPhotoRepositoryMockRecorder) ListPhotosWithoutAITags(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPhotosWithoutAITags", reflect.TypeOf((*MockPhotoRepository)(nil).ListPhotosWithoutAITags), limit)
}

// ListPhotosPendingAnalysis mocks base method.
func (m *MockPhotoRepository) ListPhotosPendingAnalysis(limit int) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPhotosPendingAnalysis", limit)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPhotosPendingAnalysis indicates an expected call of ListPhotosPendingAnalysis.
func (mr *MockPhotoRepositoryMockRecorder) ListPhotosPendingAnalysis(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPhotosPendingAnalysis", reflect.TypeOf((*MockPhotoRepository)(nil).ListPhotosPendingAnalysis), limit)
}

// SavePhotoAnalysis mocks base method.
func (m *MockPhotoRepository) SavePhotoAnalysis(analysis domain.PhotoAnalysis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePhotoAnalysis", analysis)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePhotoAnalysis indicates an expected call of SavePhotoAnalysis.
func (mr *MockPhotoRepositoryMockRecorder) SavePhotoAnalysis(analysis interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePhotoAnalysis", reflect.TypeOf((*MockPhotoRepository)(nil).SavePhotoAnalysis), analysis)
}

// GetPhotoAnalysis mocks base method.
func (m *MockPhotoRepository) GetPhotoAnalysis(photoId string) (*domain.PhotoAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoAnalysis", photoId)
	ret0, _ := ret[0].(*domain.PhotoAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotoAnalysis indicates an expected call of GetPhotoAnalysis.
func (mr *MockPhotoRepositoryMockRecorder) GetPhotoAnalysis(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoAnalysis", reflect.TypeOf((*MockPhotoRepository)(nil).GetPhotoAnalysis), photoId)
}

// GetPhotoIndexCache mocks base method.
func (m *MockPhotoRepository) GetPhotoIndexCache() (map[string]struct{ FileHash string; FileModifiedTime int64 }, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoIndexCache")
	ret0, _ := ret[0].(map[string]struct{ FileHash string; FileModifiedTime int64 })
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotoIndexCache indicates an expected call of GetPhotoIndexCache.
func (mr *MockPhotoRepositoryMockRecorder) GetPhotoIndexCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoIndexCache", reflect.TypeOf((*MockPhotoRepository)(nil).GetPhotoIndexCache))
}

// HidePhoto mocks base method.
func (m *MockPhotoRepository) HidePhoto(photoId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HidePhoto", photoId)
	ret0, _ := ret[0].(error)
	return ret0
}

// HidePhoto indicates an expected call of HidePhoto.
func (mr *MockPhotoRepositoryMockRecorder) HidePhoto(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HidePhoto", reflect.TypeOf((*MockPhotoRepository)(nil).HidePhoto), photoId)
}

// MockPhotoService is a mock of PhotoService interface.
type MockPhotoService struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoServiceMockRecorder
}

// MockPhotoServiceMockRecorder is the mock recorder for MockPhotoService.
type MockPhotoServiceMockRecorder struct {
	mock *MockPhotoService
}

// NewMockPhotoService creates a new mock instance.
func NewMockPhotoService(ctrl *gomock.Controller) *MockPhotoService {
	mock := &MockPhotoService{ctrl: ctrl}
	mock.recorder = &MockPhotoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoService) EXPECT() *MockPhotoServiceMockRecorder {
	return m.recorder
}

// BatchUpdatePhotoTags mocks base method.
func (m *MockPhotoService) BatchUpdatePhotoTags(photoIds, tags []string, operation string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdatePhotoTags", photoIds, tags, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdatePhotoTags indicates an expected call of BatchUpdatePhotoTags.
func (mr *MockPhotoServiceMockRecorder) BatchUpdatePhotoTags(photoIds, tags, operation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdatePhotoTags", reflect.TypeOf((*MockPhotoService)(nil).BatchUpdatePhotoTags), photoIds, tags, operation)
}

// DeletePhoto mocks base method.
func (m *MockPhotoService) DeletePhoto(photoId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePhoto", photoId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePhoto indicates an expected call of DeletePhoto.
func (mr *MockPhotoServiceMockRecorder) DeletePhoto(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePhoto", reflect.TypeOf((*MockPhotoService)(nil).DeletePhoto), photoId)
}

// DownloadPhotos mocks base method.
func (m *MockPhotoService) DownloadPhotos(photoIds []string, writer io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadPhotos", photoIds, writer)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadPhotos indicates an expected call of DownloadPhotos.
func (mr *MockPhotoServiceMockRecorder) DownloadPhotos(photoIds, writer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadPhotos", reflect.TypeOf((*MockPhotoService)(nil).DownloadPhotos), photoIds, writer)
}

// EmptyTrash mocks base method.
func (m *MockPhotoService) EmptyTrash() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmptyTrash")
	ret0, _ := ret[0].(error)
	return ret0
}

// EmptyTrash indicates an expected call of EmptyTrash.
func (mr *MockPhotoServiceMockRecorder) EmptyTrash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmptyTrash", reflect.TypeOf((*MockPhotoService)(nil).EmptyTrash))
}

// GetAllTags mocks base method.
func (m *MockPhotoService) GetAllTags() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTags")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTags indicates an expected call of GetAllTags.
func (mr *MockPhotoServiceMockRecorder) GetAllTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTags", reflect.TypeOf((*MockPhotoService)(nil).GetAllTags))
}

// GetDuplicatePhotos mocks base method.
func (m *MockPhotoService) GetDuplicatePhotos() ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDuplicatePhotos")
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDuplicatePhotos indicates an expected call of GetDuplicatePhotos.
func (mr *MockPhotoServiceMockRecorder) GetDuplicatePhotos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDuplicatePhotos", reflect.TypeOf((*MockPhotoService)(nil).GetDuplicatePhotos))
}

// GetGeodata mocks base method.
func (m *MockPhotoService) GetGeodata(north, south, east, west float64) ([]domain.PhotoGeoData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeodata", north, south, east, west)
	ret0, _ := ret[0].([]domain.PhotoGeoData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeodata indicates an expected call of GetGeodata.
func (mr *MockPhotoServiceMockRecorder) GetGeodata(north, south, east, west interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeodata", reflect.TypeOf((*MockPhotoService)(nil).GetGeodata), north, south, east, west)
}

// GetPhoto mocks base method.
func (m *MockPhotoService) GetPhoto(photoId string, includeThumbnail bool) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhoto", photoId, includeThumbnail)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhoto indicates an expected call of GetPhoto.
func (mr *MockPhotoServiceMockRecorder) GetPhoto(photoId, includeThumbnail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhoto", reflect.TypeOf((*MockPhotoService)(nil).GetPhoto), photoId, includeThumbnail)
}

// GetTimeline mocks base method.
func (m *MockPhotoService) GetTimeline() ([]domain.TimelineEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeline")
	ret0, _ := ret[0].([]domain.TimelineEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeline indicates an expected call of GetTimeline.
func (mr *MockPhotoServiceMockRecorder) GetTimeline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeline", reflect.TypeOf((*MockPhotoService)(nil).GetTimeline))
}

// ListFavoritePhotos mocks base method.
func (m *MockPhotoService) ListFavoritePhotos(fromId string, limit int, includeThumbnail bool, startDate, endDate string) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavoritePhotos", fromId, limit, includeThumbnail, startDate, endDate)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLowQualityPhotos mocks base method.
func (m *MockPhotoService) ListLowQualityPhotos(fromId string, limit int, includeThumbnail bool) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLowQualityPhotos", fromId, limit, includeThumbnail)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScorePhotoQuality mocks base method.
func (m *MockPhotoService) ScorePhotoQuality(photoId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScorePhotoQuality", photoId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScorePhotoQuality indicates an expected call of ScorePhotoQuality.
func (mr *MockPhotoServiceMockRecorder) ScorePhotoQuality(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScorePhotoQuality", reflect.TypeOf((*MockPhotoService)(nil).ScorePhotoQuality), photoId)
}

// ScoreAllPhotoQuality mocks base method.
func (m *MockPhotoService) ScoreAllPhotoQuality(batchSize int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScoreAllPhotoQuality", batchSize)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScoreAllPhotoQuality indicates an expected call of ScoreAllPhotoQuality.
func (mr *MockPhotoServiceMockRecorder) ScoreAllPhotoQuality(batchSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScoreAllPhotoQuality", reflect.TypeOf((*MockPhotoService)(nil).ScoreAllPhotoQuality), batchSize)
}

// ListLowQualityPhotos indicates an expected call of ListLowQualityPhotos.
func (mr *MockPhotoServiceMockRecorder) ListLowQualityPhotos(fromId, limit, includeThumbnail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLowQualityPhotos", reflect.TypeOf((*MockPhotoService)(nil).ListLowQualityPhotos), fromId, limit, includeThumbnail)
}

// ListFavoritePhotos indicates an expected call of ListFavoritePhotos.
func (mr *MockPhotoServiceMockRecorder) ListFavoritePhotos(fromId, limit, includeThumbnail, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavoritePhotos", reflect.TypeOf((*MockPhotoService)(nil).ListFavoritePhotos), fromId, limit, includeThumbnail, startDate, endDate)
}

// ListPhotos mocks base method.
func (m *MockPhotoService) ListPhotos(fromId string, limit int, includeThumbnail bool, startDate, endDate, mediaType string) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPhotos", fromId, limit, includeThumbnail, startDate, endDate, mediaType)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPhotos indicates an expected call of ListPhotos.
func (mr *MockPhotoServiceMockRecorder) ListPhotos(fromId, limit, includeThumbnail, startDate, endDate, mediaType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPhotos", reflect.TypeOf((*MockPhotoService)(nil).ListPhotos), fromId, limit, includeThumbnail, startDate, endDate, mediaType)
}

// ListPhotosByTags mocks base method.
func (m *MockPhotoService) ListPhotosByTags(tags []string, fromId string, limit int, includeThumbnail bool) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPhotosByTags", tags, fromId, limit, includeThumbnail)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPhotosByTags indicates an expected call of ListPhotosByTags.
func (mr *MockPhotoServiceMockRecorder) ListPhotosByTags(tags, fromId, limit, includeThumbnail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPhotosByTags", reflect.TypeOf((*MockPhotoService)(nil).ListPhotosByTags), tags, fromId, limit, includeThumbnail)
}

// ListPhotosInAlbum mocks base method.
func (m *MockPhotoService) ListPhotosInAlbum(albumId, fromId string, limit int, includeThumbnail bool, startDate, endDate, mediaType string) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPhotosInAlbum", albumId, fromId, limit, includeThumbnail, startDate, endDate, mediaType)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPhotosInAlbum indicates an expected call of ListPhotosInAlbum.
func (mr *MockPhotoServiceMockRecorder) ListPhotosInAlbum(albumId, fromId, limit, includeThumbnail, startDate, endDate, mediaType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPhotosInAlbum", reflect.TypeOf((*MockPhotoService)(nil).ListPhotosInAlbum), albumId, fromId, limit, includeThumbnail, startDate, endDate, mediaType)
}

// ListTrashPhotos mocks base method.
func (m *MockPhotoService) ListTrashPhotos(fromId string, limit int, includeThumbnail bool) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrashPhotos", fromId, limit, includeThumbnail)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrashPhotos indicates an expected call of ListTrashPhotos.
func (mr *MockPhotoServiceMockRecorder) ListTrashPhotos(fromId, limit, includeThumbnail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrashPhotos", reflect.TypeOf((*MockPhotoService)(nil).ListTrashPhotos), fromId, limit, includeThumbnail)
}

// PerformPhotoIndex mocks base method.
func (m *MockPhotoService) PerformPhotoIndex(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PerformPhotoIndex", ctx)
}

// PerformPhotoIndex indicates an expected call of PerformPhotoIndex.
func (mr *MockPhotoServiceMockRecorder) PerformPhotoIndex(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformPhotoIndex", reflect.TypeOf((*MockPhotoService)(nil).PerformPhotoIndex), ctx)
}

// PhotoBinary mocks base method.
func (m *MockPhotoService) PhotoBinary(photoId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhotoBinary", photoId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PhotoBinary indicates an expected call of PhotoBinary.
func (mr *MockPhotoServiceMockRecorder) PhotoBinary(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhotoBinary", reflect.TypeOf((*MockPhotoService)(nil).PhotoBinary), photoId)
}

// PhotoCount mocks base method.
func (m *MockPhotoService) PhotoCount(albumId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhotoCount", albumId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PhotoCount indicates an expected call of PhotoCount.
func (mr *MockPhotoServiceMockRecorder) PhotoCount(albumId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhotoCount", reflect.TypeOf((*MockPhotoService)(nil).PhotoCount), albumId)
}

// PhotoThumbnail mocks base method.
func (m *MockPhotoService) PhotoThumbnail(photoId string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhotoThumbnail", photoId)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PhotoThumbnail indicates an expected call of PhotoThumbnail.
func (mr *MockPhotoServiceMockRecorder) PhotoThumbnail(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhotoThumbnail", reflect.TypeOf((*MockPhotoService)(nil).PhotoThumbnail), photoId)
}

// PhotoThumbnailBytes mocks base method.
func (m *MockPhotoService) PhotoThumbnailBytes(photoId string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhotoThumbnailBytes", photoId)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PhotoThumbnailBytes indicates an expected call of PhotoThumbnailBytes.
func (mr *MockPhotoServiceMockRecorder) PhotoThumbnailBytes(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhotoThumbnailBytes", reflect.TypeOf((*MockPhotoService)(nil).PhotoThumbnailBytes), photoId)
}

// PhotoThumbnailPath mocks base method.
func (m *MockPhotoService) PhotoThumbnailPath(photoId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhotoThumbnailPath", photoId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PhotoThumbnailPath indicates an expected call of PhotoThumbnailPath.
func (mr *MockPhotoServiceMockRecorder) PhotoThumbnailPath(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhotoThumbnailPath", reflect.TypeOf((*MockPhotoService)(nil).PhotoThumbnailPath), photoId)
}

// PhotoThumbnails mocks base method.
func (m *MockPhotoService) PhotoThumbnails(photoIds []string) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhotoThumbnails", photoIds)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PhotoThumbnails indicates an expected call of PhotoThumbnails.
func (mr *MockPhotoServiceMockRecorder) PhotoThumbnails(photoIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhotoThumbnails", reflect.TypeOf((*MockPhotoService)(nil).PhotoThumbnails), photoIds)
}

// PurgeExpiredTrash mocks base method.
func (m *MockPhotoService) PurgeExpiredTrash(cutoff time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeExpiredTrash", cutoff)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeExpiredTrash indicates an expected call of PurgeExpiredTrash.
func (mr *MockPhotoServiceMockRecorder) PurgeExpiredTrash(cutoff interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeExpiredTrash", reflect.TypeOf((*MockPhotoService)(nil).PurgeExpiredTrash), cutoff)
}

// RestorePhoto mocks base method.
func (m *MockPhotoService) RestorePhoto(photoId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestorePhoto", photoId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestorePhoto indicates an expected call of RestorePhoto.
func (mr *MockPhotoServiceMockRecorder) RestorePhoto(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestorePhoto", reflect.TypeOf((*MockPhotoService)(nil).RestorePhoto), photoId)
}

// RotatePhoto mocks base method.
func (m *MockPhotoService) RotatePhoto(photoId, direction string) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotatePhoto", photoId, direction)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotatePhoto indicates an expected call of RotatePhoto.
func (mr *MockPhotoServiceMockRecorder) RotatePhoto(photoId, direction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotatePhoto", reflect.TypeOf((*MockPhotoService)(nil).RotatePhoto), photoId, direction)
}

// SavePhoto mocks base method.
func (m *MockPhotoService) SavePhoto(photo domain.PhotoFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePhoto", photo)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePhoto indicates an expected call of SavePhoto.
func (mr *MockPhotoServiceMockRecorder) SavePhoto(photo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePhoto", reflect.TypeOf((*MockPhotoService)(nil).SavePhoto), photo)
}

// SavePhotos mocks base method.
func (m *MockPhotoService) SavePhotos(photos []domain.PhotoFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePhotos", photos)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePhotos indicates an expected call of SavePhotos.
func (mr *MockPhotoServiceMockRecorder) SavePhotos(photos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePhotos", reflect.TypeOf((*MockPhotoService)(nil).SavePhotos), photos)
}

// Search mocks base method.
func (m *MockPhotoService) Search(query string, limit int) ([]*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query, limit)
	ret0, _ := ret[0].([]*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockPhotoServiceMockRecorder) Search(query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPhotoService)(nil).Search), query, limit)
}

// SetFavorite mocks base method.
func (m *MockPhotoService) SetFavorite(photoId string, favorite bool) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFavorite", photoId, favorite)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePhotoMetadata mocks base method.
func (m *MockPhotoService) UpdatePhotoMetadata(photoId string, description string, latitude, longitude *float64, dateTaken *string) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhotoMetadata", photoId, description, latitude, longitude, dateTaken)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePhotoMetadata indicates an expected call of UpdatePhotoMetadata.
func (mr *MockPhotoServiceMockRecorder) UpdatePhotoMetadata(photoId, description, latitude, longitude, dateTaken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhotoMetadata", reflect.TypeOf((*MockPhotoService)(nil).UpdatePhotoMetadata), photoId, description, latitude, longitude, dateTaken)
}

// ReverseGeocode mocks base method.
func (m *MockPhotoService) ReverseGeocode(ctx context.Context, photoId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReverseGeocode", ctx, photoId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReverseGeocode indicates an expected call of ReverseGeocode.
func (mr *MockPhotoServiceMockRecorder) ReverseGeocode(ctx, photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReverseGeocode", reflect.TypeOf((*MockPhotoService)(nil).ReverseGeocode), ctx, photoId)
}

// BatchSetFavorite mocks base method.
func (m *MockPhotoService) BatchSetFavorite(photoIds []string, favorite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSetFavorite", photoIds, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSetFavorite indicates an expected call of BatchSetFavorite.
func (mr *MockPhotoServiceMockRecorder) BatchSetFavorite(photoIds, favorite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSetFavorite", reflect.TypeOf((*MockPhotoService)(nil).BatchSetFavorite), photoIds, favorite)
}

// BatchAddToAlbum mocks base method.
func (m *MockPhotoService) BatchAddToAlbum(photoIds []string, albumId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchAddToAlbum", photoIds, albumId)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchAddToAlbum indicates an expected call of BatchAddToAlbum.
func (mr *MockPhotoServiceMockRecorder) BatchAddToAlbum(photoIds, albumId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAddToAlbum", reflect.TypeOf((*MockPhotoService)(nil).BatchAddToAlbum), photoIds, albumId)
}

// BatchDeletePhotos mocks base method.
func (m *MockPhotoService) BatchDeletePhotos(photoIds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDeletePhotos", photoIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDeletePhotos indicates an expected call of BatchDeletePhotos.
func (mr *MockPhotoServiceMockRecorder) BatchDeletePhotos(photoIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeletePhotos", reflect.TypeOf((*MockPhotoService)(nil).BatchDeletePhotos), photoIds)
}

// SetFavorite indicates an expected call of SetFavorite.
func (mr *MockPhotoServiceMockRecorder) SetFavorite(photoId, favorite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFavorite", reflect.TypeOf((*MockPhotoService)(nil).SetFavorite), photoId, favorite)
}

// UpdatePhotoTags mocks base method.
func (m *MockPhotoService) UpdatePhotoTags(photoId string, tags []string) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhotoTags", photoId, tags)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePhotoTags indicates an expected call of UpdatePhotoTags.
func (mr *MockPhotoServiceMockRecorder) UpdatePhotoTags(photoId, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhotoTags", reflect.TypeOf((*MockPhotoService)(nil).UpdatePhotoTags), photoId, tags)
}

// GenerateThumbnailForPhoto mocks base method.
func (m *MockPhotoService) GenerateThumbnailForPhoto(photoId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateThumbnailForPhoto", photoId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateThumbnailForPhoto indicates an expected call of GenerateThumbnailForPhoto.
func (mr *MockPhotoServiceMockRecorder) GenerateThumbnailForPhoto(photoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateThumbnailForPhoto", reflect.TypeOf((*MockPhotoService)(nil).GenerateThumbnailForPhoto), photoId)
}

// PhotoThumbnailPathForSize mocks base method.
func (m *MockPhotoService) PhotoThumbnailPathForSize(photoId, size string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhotoThumbnailPathForSize", photoId, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PhotoThumbnailPathForSize indicates an expected call of PhotoThumbnailPathForSize.
func (mr *MockPhotoServiceMockRecorder) PhotoThumbnailPathForSize(photoId, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhotoThumbnailPathForSize", reflect.TypeOf((*MockPhotoService)(nil).PhotoThumbnailPathForSize), photoId, size)
}

// PhotoThumbnailBytesForSize mocks base method.
func (m *MockPhotoService) PhotoThumbnailBytesForSize(photoId, size string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PhotoThumbnailBytesForSize", photoId, size)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PhotoThumbnailBytesForSize indicates an expected call of PhotoThumbnailBytesForSize.
func (mr *MockPhotoServiceMockRecorder) PhotoThumbnailBytesForSize(photoId, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PhotoThumbnailBytesForSize", reflect.TypeOf((*MockPhotoService)(nil).PhotoThumbnailBytesForSize), photoId, size)
}

// AnalyzeExistingPhotos mocks base method.
func (m *MockPhotoService) AnalyzeExistingPhotos() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeExistingPhotos")
	ret0, _ := ret[0].(error)
	return ret0
}

// AnalyzeExistingPhotos indicates an expected call of AnalyzeExistingPhotos.
func (mr *MockPhotoServiceMockRecorder) AnalyzeExistingPhotos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeExistingPhotos", reflect.TypeOf((*MockPhotoService)(nil).AnalyzeExistingPhotos))
}

// TriggerAIAnalysis mocks base method.
func (m *MockPhotoService) TriggerAIAnalysis() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerAIAnalysis")
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerAIAnalysis indicates an expected call of TriggerAIAnalysis.
func (mr *MockPhotoServiceMockRecorder) TriggerAIAnalysis() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerAIAnalysis", reflect.TypeOf((*MockPhotoService)(nil).TriggerAIAnalysis))
}

// RegenerateThumbnails mocks base method.
func (m *MockPhotoService) RegenerateThumbnails(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegenerateThumbnails", ctx)
}

// RegenerateThumbnails indicates an expected call of RegenerateThumbnails.
func (mr *MockPhotoServiceMockRecorder) RegenerateThumbnails(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegenerateThumbnails", reflect.TypeOf((*MockPhotoService)(nil).RegenerateThumbnails), ctx)
}
