// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/workspace.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.com/r1chjames/photobox/api/internal/core/domain"
)

// MockWorkspaceRepository is a mock of WorkspaceRepository interface.
type MockWorkspaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceRepositoryMockRecorder
}

// MockWorkspaceRepositoryMockRecorder is the mock recorder for MockWorkspaceRepository.
type MockWorkspaceRepositoryMockRecorder struct {
	mock *MockWorkspaceRepository
}

// NewMockWorkspaceRepository creates a new mock instance.
func NewMockWorkspaceRepository(ctrl *gomock.Controller) *MockWorkspaceRepository {
	mock := &MockWorkspaceRepository{ctrl: ctrl}
	mock.recorder = &MockWorkspaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceRepository) EXPECT() *MockWorkspaceRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockWorkspaceRepository) AddMember(workspaceID, userID string, role domain.WorkspaceRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", workspaceID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockWorkspaceRepositoryMockRecorder) AddMember(workspaceID, userID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockWorkspaceRepository)(nil).AddMember), workspaceID, userID, role)
}

// AdjustStorageUsed mocks base method.
func (m *MockWorkspaceRepository) AdjustStorageUsed(ctx context.Context, workspaceID string, delta int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustStorageUsed", ctx, workspaceID, delta)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdjustStorageUsed indicates an expected call of AdjustStorageUsed.
func (mr *MockWorkspaceRepositoryMockRecorder) AdjustStorageUsed(ctx, workspaceID, delta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustStorageUsed", reflect.TypeOf((*MockWorkspaceRepository)(nil).AdjustStorageUsed), ctx, workspaceID, delta)
}

// CreateWorkspace mocks base method.
func (m *MockWorkspaceRepository) CreateWorkspace(workspace *domain.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace", workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockWorkspaceRepositoryMockRecorder) CreateWorkspace(workspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockWorkspaceRepository)(nil).CreateWorkspace), workspace)
}

// DeleteWorkspace mocks base method.
func (m *MockWorkspaceRepository) DeleteWorkspace(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspace", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspace indicates an expected call of DeleteWorkspace.
func (mr *MockWorkspaceRepositoryMockRecorder) DeleteWorkspace(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspace", reflect.TypeOf((*MockWorkspaceRepository)(nil).DeleteWorkspace), id)
}

// GetMembership mocks base method.
func (m *MockWorkspaceRepository) GetMembership(workspaceID, userID string) (*domain.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", workspaceID, userID)
	ret0, _ := ret[0].(*domain.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockWorkspaceRepositoryMockRecorder) GetMembership(workspaceID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockWorkspaceRepository)(nil).GetMembership), workspaceID, userID)
}

// GetWorkspaceById mocks base method.
func (m *MockWorkspaceRepository) GetWorkspaceById(id string) (*domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceById", id)
	ret0, _ := ret[0].(*domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceById indicates an expected call of GetWorkspaceById.
func (mr *MockWorkspaceRepositoryMockRecorder) GetWorkspaceById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceById", reflect.TypeOf((*MockWorkspaceRepository)(nil).GetWorkspaceById), id)
}

// GetWorkspaceBySlug mocks base method.
func (m *MockWorkspaceRepository) GetWorkspaceBySlug(slug string) (*domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceBySlug", slug)
	ret0, _ := ret[0].(*domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceBySlug indicates an expected call of GetWorkspaceBySlug.
func (mr *MockWorkspaceRepositoryMockRecorder) GetWorkspaceBySlug(slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceBySlug", reflect.TypeOf((*MockWorkspaceRepository)(nil).GetWorkspaceBySlug), slug)
}

// ListMemberUsers mocks base method.
func (m *MockWorkspaceRepository) ListMemberUsers(workspaceID string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberUsers", workspaceID)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberUsers indicates an expected call of ListMemberUsers.
func (mr *MockWorkspaceRepositoryMockRecorder) ListMemberUsers(workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberUsers", reflect.TypeOf((*MockWorkspaceRepository)(nil).ListMemberUsers), workspaceID)
}

// ListMembers mocks base method.
func (m *MockWorkspaceRepository) ListMembers(workspaceID string) ([]domain.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", workspaceID)
	ret0, _ := ret[0].([]domain.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockWorkspaceRepositoryMockRecorder) ListMembers(workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockWorkspaceRepository)(nil).ListMembers), workspaceID)
}

// ListWorkspacesForUser mocks base method.
func (m *MockWorkspaceRepository) ListWorkspacesForUser(userID string) ([]domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkspacesForUser", userID)
	ret0, _ := ret[0].([]domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkspacesForUser indicates an expected call of ListWorkspacesForUser.
func (mr *MockWorkspaceRepositoryMockRecorder) ListWorkspacesForUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkspacesForUser", reflect.TypeOf((*MockWorkspaceRepository)(nil).ListWorkspacesForUser), userID)
}

// RemoveMember mocks base method.
func (m *MockWorkspaceRepository) RemoveMember(workspaceID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", workspaceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockWorkspaceRepositoryMockRecorder) RemoveMember(workspaceID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockWorkspaceRepository)(nil).RemoveMember), workspaceID, userID)
}

// UpdateMemberRole mocks base method.
func (m *MockWorkspaceRepository) UpdateMemberRole(workspaceID, userID string, role domain.WorkspaceRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", workspaceID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockWorkspaceRepositoryMockRecorder) UpdateMemberRole(workspaceID, userID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockWorkspaceRepository)(nil).UpdateMemberRole), workspaceID, userID, role)
}

// UpdateWorkspace mocks base method.
func (m *MockWorkspaceRepository) UpdateWorkspace(workspace *domain.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspace", workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkspace indicates an expected call of UpdateWorkspace.
func (mr *MockWorkspaceRepositoryMockRecorder) UpdateWorkspace(workspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspace", reflect.TypeOf((*MockWorkspaceRepository)(nil).UpdateWorkspace), workspace)
}

// MockWorkspaceService is a mock of WorkspaceService interface.
type MockWorkspaceService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceServiceMockRecorder
}

// MockWorkspaceServiceMockRecorder is the mock recorder for MockWorkspaceService.
type MockWorkspaceServiceMockRecorder struct {
	mock *MockWorkspaceService
}

// NewMockWorkspaceService creates a new mock instance.
func NewMockWorkspaceService(ctrl *gomock.Controller) *MockWorkspaceService {
	mock := &MockWorkspaceService{ctrl: ctrl}
	mock.recorder = &MockWorkspaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceService) EXPECT() *MockWorkspaceServiceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockWorkspaceService) AddMember(workspaceID, actorUserID, targetUserID string, role domain.WorkspaceRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", workspaceID, actorUserID, targetUserID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockWorkspaceServiceMockRecorder) AddMember(workspaceID, actorUserID, targetUserID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockWorkspaceService)(nil).AddMember), workspaceID, actorUserID, targetUserID, role)
}

// CanManage mocks base method.
func (m *MockWorkspaceService) CanManage(membership *domain.WorkspaceMember) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanManage", membership)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanManage indicates an expected call of CanManage.
func (mr *MockWorkspaceServiceMockRecorder) CanManage(membership interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanManage", reflect.TypeOf((*MockWorkspaceService)(nil).CanManage), membership)
}

// CreateWorkspace mocks base method.
func (m *MockWorkspaceService) CreateWorkspace(name, slug, userID string) (*domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace", name, slug, userID)
	ret0, _ := ret[0].(*domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockWorkspaceServiceMockRecorder) CreateWorkspace(name, slug, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockWorkspaceService)(nil).CreateWorkspace), name, slug, userID)
}

// DeleteWorkspace mocks base method.
func (m *MockWorkspaceService) DeleteWorkspace(workspaceID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspace", workspaceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspace indicates an expected call of DeleteWorkspace.
func (mr *MockWorkspaceServiceMockRecorder) DeleteWorkspace(workspaceID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspace", reflect.TypeOf((*MockWorkspaceService)(nil).DeleteWorkspace), workspaceID, userID)
}

// GetMembership mocks base method.
func (m *MockWorkspaceService) GetMembership(workspaceID, userID string) (*domain.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", workspaceID, userID)
	ret0, _ := ret[0].(*domain.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockWorkspaceServiceMockRecorder) GetMembership(workspaceID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockWorkspaceService)(nil).GetMembership), workspaceID, userID)
}

// GetWorkspace mocks base method.
func (m *MockWorkspaceService) GetWorkspace(workspaceID, userID string) (*domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspace", workspaceID, userID)
	ret0, _ := ret[0].(*domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspace indicates an expected call of GetWorkspace.
func (mr *MockWorkspaceServiceMockRecorder) GetWorkspace(workspaceID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspace", reflect.TypeOf((*MockWorkspaceService)(nil).GetWorkspace), workspaceID, userID)
}

// ListMembers mocks base method.
func (m *MockWorkspaceService) ListMembers(workspaceID, userID string) ([]domain.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", workspaceID, userID)
	ret0, _ := ret[0].([]domain.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockWorkspaceServiceMockRecorder) ListMembers(workspaceID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockWorkspaceService)(nil).ListMembers), workspaceID, userID)
}

// ListWorkspaces mocks base method.
func (m *MockWorkspaceService) ListWorkspaces(userID string) ([]domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkspaces", userID)
	ret0, _ := ret[0].([]domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkspaces indicates an expected call of ListWorkspaces.
func (mr *MockWorkspaceServiceMockRecorder) ListWorkspaces(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkspaces", reflect.TypeOf((*MockWorkspaceService)(nil).ListWorkspaces), userID)
}

// RemoveMember mocks base method.
func (m *MockWorkspaceService) RemoveMember(workspaceID, actorUserID, targetUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", workspaceID, actorUserID, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockWorkspaceServiceMockRecorder) RemoveMember(workspaceID, actorUserID, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockWorkspaceService)(nil).RemoveMember), workspaceID, actorUserID, targetUserID)
}

// UpdateMemberRole mocks base method.
func (m *MockWorkspaceService) UpdateMemberRole(workspaceID, actorUserID, targetUserID string, role domain.WorkspaceRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", workspaceID, actorUserID, targetUserID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockWorkspaceServiceMockRecorder) UpdateMemberRole(workspaceID, actorUserID, targetUserID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockWorkspaceService)(nil).UpdateMemberRole), workspaceID, actorUserID, targetUserID, role)
}

// UpdateWorkspace mocks base method.
func (m *MockWorkspaceService) UpdateWorkspace(workspaceID, userID, name string) (*domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspace", workspaceID, userID, name)
	ret0, _ := ret[0].(*domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkspace indicates an expected call of UpdateWorkspace.
func (mr *MockWorkspaceServiceMockRecorder) UpdateWorkspace(workspaceID, userID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspace", reflect.TypeOf((*MockWorkspaceService)(nil).UpdateWorkspace), workspaceID, userID, name)
}
