apiVersion: v2
name: photobox
description: A Helm chart for the Photobox application stack
type: application
version: 0.2.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "15.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: database.enabled
