# Default values for photobox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/r1chjames/photobox
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-login
nameOverride: "photobox"
fullnameOverride: "photobox"

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.255
  port: 8080

env:
  DB_HOST: photobox-mysql
  DB_USER: photobox_usr
  DB_PASSWORD: password
  DB_NAME: photobox_db
  PHOTO_DIR: /photos
  API_BASE_PATH: /api

hostMounts:
  - name: photos
    hostPath: /home/rich/Pictures
    mountPath: /photos

serviceAccount:
  create: true

persistence:
  enabled: false

ingress:
  enabled: false
  annotations:
  hosts:
    - host: ""
      paths:
        - 

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

mysql:
  enabled: true
  initdbScripts:
    photobox.sql: |
      CREATE DATABASE photobox_db;
      CREATE USER 'photobox_usr'@'%' IDENTIFIED BY 'password';
      GRANT USAGE ON *.* TO 'photobox_usr'@'%';
      GRANT ALL privileges ON photobox_db.* TO 'photobox_usr'@'%';
      USE photobox_db;
      CREATE TABLE albums (
          id                      VARCHAR(36) PRIMARY KEY,
          name                    VARCHAR(255) NOT NULL,
          description             VARCHAR(255),
          tags                    VARCHAR(255),
          metadata                JSON
      );
      CREATE TABLE photos (
          id                      VARCHAR(100) PRIMARY KEY,
          name                    VARCHAR(255) NOT NULL,
          filesystemPath          VARCHAR(255) NOT NULL,
          albumId                 VARCHAR(36) NOT NULL,
          tags                    VARCHAR(255),
          metadata                JSON,

          FOREIGN KEY (albumId) REFERENCES albums(id)
      );
      CREATE TABLE settings (
          setting                 VARCHAR(255) NOT NULL,
          value                   VARCHAR(255) NOT NULL
      );
      CREATE TABLE jobs (
          job                     VARCHAR(255) NOT NULL,
          running                 BOOLEAN,
          lastRun                 VARCHAR(50)
      );
      INSERT INTO jobs VALUES ('Photo_index', false, null);
      INSERT INTO settings VALUES ('api_base_path', '/api');

  replication:
    enabled: false
  master:
    readinessProbe:
      enabled: false
  slave:
    replicas: 0
  root:
    password: password
    forcePassword: true