apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photobox.fullname" . }}-api
  labels:
    {{- include "photobox.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.api.secrets.dbPassword | quote }}
  TOKEN: {{ .Values.api.secrets.token | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.api.secrets.adminPassword | quote }}
