apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photobox.secretName" . }}
  labels:
    {{- include "photobox.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  TOKEN: {{ .Values.secrets.token | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  S3_ENDPOINT: {{ .Values.secrets.s3Endpoint | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  S3_BUCKET: {{ .Values.secrets.s3Bucket | quote }}
