{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "photobox.serviceAccountName" . }}
  labels:
{{ include "photobox.labels" . | indent 4 }}
{{- end -}}
