apiVersion: v1
kind: Service
metadata:
  name: {{ include "photobox.fullname" . }}
  labels:
    {{- include "photobox.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
spec:
  type: {{ .Values.webapp.service.type }}
  {{- if and (eq .Values.webapp.service.type "LoadBalancer") .Values.webapp.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.webapp.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "photobox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
