apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photobox.fullname" . }}-webapp
  labels:
    {{- include "photobox.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      {{- include "photobox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webapp
  template:
    metadata:
      labels:
        {{- include "photobox.labels" . | nindent 8 }}
        app.kubernetes.io/component: webapp
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "photobox.serviceAccountName" . }}
      containers:
        - name: webapp
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
          imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webapp.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.webapp.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
